### ISSUE TITLE
How do I run a command as sudo?

### ISSUE THREAD

**Issue by mhenrixon** [test-kitchen/busser-serverspec#20]
Since I accidentally upgraded the busser I can't run any specs anymore. It keeps asking for sudo password prompt and I have no way of providing it back. 

How do I turn on the previous functionality with not asking for the password?
I tried the following but it doesn't accept anything I write:

![app-server zsh 2014-10-20 22-36-41](https://cloud.githubusercontent.com/assets/106795/4708617/f4336528-5898-11e4-9904-25d8f3a58e79.png)

In a spec_helper I have the following:

``` ruby
require 'serverspec'

set :backend, :exec
set :path, '/sbin:/usr/sbin:/usr/local/sbin:$PATH'
set :sudo_password, 'vagrant'
```

Doesn't seem to help and I have no idea if that is the password test kitchen sets for my vagrant user.

I simply can't start the busser with

``` yml
# .kitchen.yml
busser:
  sudo: true
```

anymore.

**Comment by gsaslis** [comment]
Thanks for this @mhenrixon !! i was also using the sudo cookbook, and my conf wasn't including the vagrant user, so simply adding the vagrant user solved my issue.. 

```
    "authorization": {
      "sudo": {
        "users": ["jenkins", "vagrant"],
        "passwordless": "true"
      }
    },
```

Thanks again!
