### ISSUE TITLE
Tests for all suites

### ISSUE THREAD

**Issue by arifcse019** [test-kitchen/busser-serverspec#26]
Hi,

Is it possible to run some tests for all suites? Then it saves from duplicating the tests those are applicable for all suites

Arif

**Comment by cl-lab-k** [comment]
i think this feature is not only in busser-serverspec but also in test-kitchen / busser.
would you please open issue at test-kitchen for a starter?

**Comment by arifcse019** [comment]
You mean here? https://github.com/test-kitchen/busser

**Comment by cl-lab-k** [comment]
https://github.com/test-kitchen/test-kitchen or https://github.com/test-kitchen/busser
your saying is not specific for busser-serverspec.

**Comment by bbergstrom** [comment]
https://github.com/test-kitchen/busser/issues/26

**Comment by bbergstrom** [comment]
This doesn't run some tests in all suites, but at least lets you share logic across all suites: https://github.com/test-kitchen/test-kitchen/pull/134
