### ISSUE TITLE
test-kitchen check for ports broken on newer versions?

### ISSUE THREAD

**Issue by jslusher** [test-kitchen/busser-serverspec#32]
I know these tests used to work, but they've been failing at some point and I'm trying to figure out if it's because I upgraded or if there's something else.

I have this in my _spec.rb file:

    # test ssh port
    describe port(22) do
      it { should be_listening }
    end

I can ssh onto the server fine. I know the port is listening, but I get this when I run kitchen verify:

           Failures:

         1) Port "22" should be listening
            Failure/Error: it { should be_listening }
              expected Port "22" to be listening
            # /tmp/verifier/suites/serverspec/base_spec.rb:5:in `block (2 levels) in <top (required)>'

**Comment by cl-lab-k** [comment]
i could not reproduced it.
if upgraded test-kitchen occurs this situation, please file this issue to test-kitchen/test-kitchen .

**Comment by cl-lab-k** [comment]
no response, closing.
