### ISSUE TITLE
travis failure since 2015/8

### ISSUE THREAD

**Issue by d-higuchi** [test-kitchen/busser-serverspec#40]
maybe aruba after v0.9.0.pre

**Comment by dai-vdr** [comment]
ebe978d Pin versions of aruba and cucumber , it is inspired by test-kitchen/busser-cucumber@cd3e6b3 , thanks to Peter Gallagher
but still travis failure.

**Comment by cl-lab-k** [comment]
ebe978d Pin versions of aruba and cucumber , it is inspired by test-kitchen/busser-cucumber@cd3e6b3 , thanks to Peter Gallagher
but still travis failure.
