### ISSUE TITLE
Formal request to take over maintenance

### ISSUE THREAD

**Issue by coderanger** [test-kitchen/busser-serverspec#43]
Since this project could use a little love, I would like to formally request to take over maintenance duties. I probably am the last major hold-out on Serverspec in whatever passes for the Kitchen core team, and will remain a such for the foreseeable future as InSpec doesn't offer the RSpec goop I use a lot of.

**Comment by cl-lab-k** [comment]
I accept your request. Thank you for your kind offer.

**Comment by coderanger** [comment]
Awesome, can you add me as a repository admin?

**Comment by cl-lab-k** [comment]
Added you with admin permission.

**Comment by coderanger** [comment]
Thanks! And thanks so much for all your hard work over the years.
