### ISSUE TITLE
[Question] Keeping shared examples in git

### ISSUE THREAD

**Issue by thunder-spb** [test-kitchen/busser-serverspec#48]
Hi guys,

We're using kitchen to test our Salt-Stack formulas. We have some shared examples, like for nginx or service shared functions, so is there any mechanism in kitchen to get such examples from git as a dependency? Is there any detailed description on that? Currently we have to add such common shared examples in each formula :(

ps: we use serverspec currently, looks like inspec could cover all our needs?

Thanks,

**Comment by Poohblah** [comment]
There are not any that I'm aware of.  My team had to build out our own support for loading shared examples from external git repos; we have a very custom spec_helper for this purpose.
