### ISSUE TITLE
Bundler version in postinstall

### ISSUE THREAD

**Issue by achamo** [test-kitchen/busser-serverspec#53]
Hi,

I'm using busser and busser-serverspec with Chef 12.13.81 on CentOS 7.
Since today, I'm facing this issue:

```
-----> Installing Busser (busser)
Fetching: thor-0.19.0.gem (100%)
       Successfully installed thor-0.19.0
Fetching: busser-0.7.1.gem (100%)
       Successfully installed busser-0.7.1
       2 gems installed
-----> Installing Busser plugin: busser-serverspec
       Plugin serverspec installed (version 0.5.10)
-----> Running postinstall for serverspec plugin
       /opt/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/installer.rb:619:in `ensure_required_rubygems_version_met': bundler requires RubyGems version >= 3.0.0. Try 'gem update --system' to update RubyGems itself. (Gem::InstallError)
        from /opt/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/installer.rb:828:in `pre_install_checks'
        from /opt/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/installer.rb:279:in `install'
        from /opt/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/resolver/specification.rb:97:in `install'
        from /opt/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/request_set.rb:166:in `block in install'
        from /opt/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/request_set.rb:156:in `each'
        from /opt/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/request_set.rb:156:in `install'
        from /opt/chef/embedded/lib/ruby/site_ruby/2.3.0/rubygems/dependency_installer.rb:405:in `install'
        from /tmp/verifier/gems/gems/busser-0.7.1/lib/busser/rubygems.rb:44:in `install_gem'
        from /tmp/verifier/gems/gems/busser-0.7.1/lib/busser/helpers.rb:57:in `install_gem'
        from /tmp/verifier/gems/gems/busser-serverspec-0.5.10/lib/busser/runner_plugin/serverspec.rb:28:in `block in <class:Serverspec>'
```

In this line https://github.com/test-kitchen/busser-serverspec/blob/master/lib/busser/runner_plugin/serverspec.rb#L28 busser-serverspec installs bundler at the last version.
How can we pin a version for bundler ?
I can't upgrade rubygems.

**Comment by lzecca78** [comment]
Having the same issue of @achamo  here. Should be perfect be able to ping bundler version, due to latest upgrade of bundler, quite every logic now should take in consideration the pinning of the version

**Comment by joe4dev** [comment]
same issue here causing my CI build failures

**Comment by joe4dev** [comment]
I get some more specific log output (but basically the same):

```
/opt/chef/embedded/lib/ruby/2.5.0/rubygems/installer.rb:629:in `ensure_required_rubygems_version_met': The last version of bundler (>= 0) to support your Ruby & RubyGems was 1.17.3. Try installing it with `gem install bundler -v 1.17.3` (Gem::RuntimeRequirementNotMetError)
  bundler requires RubyGems version >= 3.0.0. The current RubyGems version is 2.7.6. Try 'gem update --system' to update RubyGems itself.
  from /opt/chef/embedded/lib/ruby/2.5.0/rubygems/installer.rb:852:in `pre_install_checks'
```

**Comment by joe4dev** [comment]
Either pinning bundler or updating RubyGems before via `'gem update --system'` should fix this issue.

**Comment by lzecca78** [comment]
@WheresAlice yes, the new gem binary does not support `--no-ri` nor `--no-rdoc` option, that is something embedded in 99% of configurations. I use kitchen with puppet and i cannot move forward with the version of gem because of default puppet provider gem set in every `gem install` command the `--no-ri --no-rdoc`. Is really a mess.

**Comment by joe4dev** [comment]
Does this work instead [here](https://github.com/test-kitchen/busser-serverspec/blob/master/lib/busser/runner_plugin/serverspec.rb#L28)?
`install_gem('bundler', '1.17.3')`

Following the `install_gem` plugin hook from:
* https://github.com/test-kitchen/busser/blob/master/lib/busser/helpers.rb#L56
* https://github.com/test-kitchen/busser/blob/master/lib/busser/rubygems.rb#L36

**Comment by WheresAlice** [comment]
That change would almost certainly work for my use-case, with the older version of Ruby embedded in Chef.  It may not work or may cause issues for people with newer versions of Ruby.

**Comment by caarlos0** [comment]
any workarounds?

**Comment by WheresAlice** [comment]
The work around we have put in place is to configure our docker images to use our local internal ruby gem repo which doesn't have the newer version of bundler yet. This obviously isn't a suitable workaround for everyone.

Going forward our workaround will be to migrate from serverspec to inspec. Which is a fairly straightforward migration, and comes with other benefits.

**Comment by caarlos0** [comment]
I'm going for the inspec thing...

**Comment by jmangs** [comment]
I've verified that `install_gem('bundler', '~> 1.17')` works as a fix as @joe4dev mentioned above. You can do a variation like this to verify it works locally:
```
$ sudo sed -i "28s/install_gem('bundler')/install_gem('bundler', '~> 1.17')/" /tmp/verifier/gems/gems/busser-serverspec-0.5.10/lib/busser/runner_plugin/serverspec.rb
```
This works for me. I've opened a PR with the relevant change.

**Comment by MarkRoddy** [comment]
If anyone needs an immediate work around, it appears that a second invocation of `kitchen verify ...` isn't susceptible to the failed attempt to install Bundler. For the time being we're working around this by running the verify command twice and allowing the first invocation to fail.  This is the Rake task we're using at the moment:
```ruby
task :testkitchen, [:suite] do |_t, args|
  error = nil
  begin
    sh "kitchen converge #{args[:suite]}"
    sh "kitchen verify #{args[:suite]} || true"
    sh "kitchen verify #{args[:suite]}"
  rescue StandardError => e
    error = e
  ensure
    sh "kitchen destroy #{args[:suite]}"
    raise error unless error.nil?
  end
end
```

**Comment by dthorsen** [comment]
This PR should fix this issue for most folks: https://github.com/bundler/bundler/pull/6867

**Comment by dthorsen** [comment]
Bundler 2.0.1 has been released and my test-kitchen runs are succeeding now. Your mileage may vary depending on the ruby gem version you have. I am running chefdk 2.4.17 with kitchen 1.19.2 and it is now working.

**Comment by lzecca78** [comment]
@dthorsen , the bundler version 2.0.1 has been released in order to avoid those kind of problems: ```Relaxed RubyGems requirement to >= 2.5.0 (#6867)```. Thanks to this, now, everything is back to work.

**Comment by achamo** [comment]
Yep with the last bundler release, this issue is irrelevant.

**Comment by jmangs** [comment]
An unfortunate side-effect of the latest `bundler` release is that you will need to use Ruby 2.3.0 or greater which means Chef 11 support is basically broken:

```
-----> Running postinstall for serverspec plugin

       /opt/chef/embedded/lib/ruby/site_ruby/1.9.1/rubygems/installer.rb:533:in `ensure_required_ruby_version_met': bundler requires Ruby version >= 2.3.0. (Gem::InstallError)
```
At this point we're just going to force people to move to InSpec given how many Ruby dependency problems there are (we've patched other ones via `test-kitchen` but this one is in the post-install step which isn't easy to address).
