### ISSUE TITLE
Be able to use chef attributes in serverspec

### ISSUE THREAD

**Issue by guilhem** [test-kitchen/busser-serverspec#8]
For now we are using tests to manage if executable is installed with:

```
describe command('which nodejs') do
  it { should return_exit_status 0 }
end
```

But that's quite limited, we don't know if version installed is what we really want.
Something really good can be to be able to use:

```
describe command('nodejs -v') do
  it { should return_stdout "v#{node['nodejs']['version']}" }
end
```

It can be related to this:
https://github.com/serverspec/serverspec/issues/155

I don't know if it must be manage by serverspec (be able to parse chef), or a work for busser to be able to export in serverspec yml format.
But this feature is clearly a must-have.

PS: If it's already possible, don't hesitate to tell me how :)
PS bis: another [ticket](https://github.com/test-kitchen/test-kitchen/issues/174) talk about it... but I really don't understand why using chef attributes in tests is a bad idea... really

**Comment by renier** [comment]
Much easier. Just put this in a spec support file and require it from your tests:

```ruby
class MyHash < Hash
  alias_method :orig_subscript, :'[]'
  define_method(:'[]') do |subscript|
    send(:'[]=', subscript, MyHash.new) unless orig_subscript(subscript)
    orig_subscript(subscript)
  end
end

default = node = override = MyHash.new

eval IO.read('/tmp/kitchen/cookbooks/my_cookbook/attributes/default.rb')

# default hash has all the values now.
```

**Comment by xacaxulu** [comment]
I would move to using control_groups with the latest Chef 0.5.0 release candidate. You can do away with serverspec and simply write in-line control_group audits, which are an abstraction of serverspec.

https://docs.chef.io/analytics.html#controls

**Comment by BBK-PiJ-2015-14** [comment]
Combination of cookbook attributes and kitchen suite attributes would be ideal. This way you get whatever both cookbook specific and can add any rutime attributes or have different ones depending on which suite you execute.

Would anyone know how to retrieve suite attributes?
`
suites:
  - name: default
    run_list:
      - recipe[my_windows_cookbook::default]
    attributes: { 'NodeA': { 'AttributeZZ':'ValueZZ', 'NodeAA': { 'AttributeXX' : 'ValueXX' } } }`

**Comment by xmik** [comment]
There is a solution, described here: https://github.com/test-kitchen/test-kitchen/issues/858 , but do read the last comment from there too.
